//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.27 at 03:10:09 PM GMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://tus.ie/students", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ie.tus.students;
